WITH t1 AS (
SELECT * FROM sfcu.GL_700s_assets WHERE GL_ACCT_NUM = 701.03 AND YEAR(TRANS_DATE)=2010
)
SELECT GL_ACCT_NUM,t1.TRANS_DATE, t1.END_BAL FROM t1 WHERE t1.TRANS_DATE =  (SELECT MAX(TRANS_DATE) FROM t1) LIMIT 1; 
